// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfXFgYbw8uYLjJoaNol8-BIDjden63Mxc',
    appId: '1:1008840384942:web:d40ed3b0cb0396af9ae83f',
    messagingSenderId: '1008840384942',
    projectId: 'deimox-autenticacion',
    authDomain: 'deimox-autenticacion.firebaseapp.com',
    storageBucket: 'deimox-autenticacion.appspot.com',
    measurementId: 'G-VGR506H6K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP770DVRWh8DjgLna056N7d26A7zOv30s',
    appId: '1:1008840384942:android:6844e3798b0b74b89ae83f',
    messagingSenderId: '1008840384942',
    projectId: 'deimox-autenticacion',
    storageBucket: 'deimox-autenticacion.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfXFgYbw8uYLjJoaNol8-BIDjden63Mxc',
    appId: '1:1008840384942:web:1d641506242b0d489ae83f',
    messagingSenderId: '1008840384942',
    projectId: 'deimox-autenticacion',
    authDomain: 'deimox-autenticacion.firebaseapp.com',
    storageBucket: 'deimox-autenticacion.appspot.com',
    measurementId: 'G-VMXDKLRQML',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPApF6jFfI0u5vlfAVDUbzPmGy9_7LE8E',
    appId: '1:1008840384942:ios:7e6784d88c072f949ae83f',
    messagingSenderId: '1008840384942',
    projectId: 'deimox-autenticacion',
    storageBucket: 'deimox-autenticacion.appspot.com',
    iosBundleId: 'com.deimox.deimoxapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPApF6jFfI0u5vlfAVDUbzPmGy9_7LE8E',
    appId: '1:1008840384942:ios:7e6784d88c072f949ae83f',
    messagingSenderId: '1008840384942',
    projectId: 'deimox-autenticacion',
    storageBucket: 'deimox-autenticacion.appspot.com',
    iosBundleId: 'com.deimox.deimoxapp',
  );

}